### ISSUE TITLE
Add support for bitwise operators

### ISSUE THREAD

**Issue by ShengXiangXiong** [expr-lang/expr#207]
```
val := `1 & 1`
complie, err := expr.Compile(val)
r, err := expr.Run(complie,env)
if err!=nil {
fmt.Printf("%+v", err)
}
if v, ok := r.(int); ok {
fmt.Printf("%+v", v)
}
```

![image](https://user-images.githubusercontent.com/20365712/140894195-1b6d9a69-b02e-426b-abef-ee08002ee9de.png)

**Comment by antonmedv** [comment]
Nope, no bit operators.

**Comment by ShengXiangXiong** [comment]
Can this feature be added in the future

**Comment by ShengXiangXiong** [comment]
> Nope, no bit operators.

Can this feature be added in the future

**Comment by antonmedv** [comment]
Maybe.

**Comment by antonmedv** [comment]
I'm thinking to add bit ops with such functions:

- shl(int, int) – signed shift left
- shr(int, int) – signed shift right
- ushr(int, int) – unsigned shift right
- band(int, int) – bitwise AND
- bor(int, int) – bitwise OR
- xor(int) – bitwise XOR
- inv(int) – bitwise inversion

**Comment by antonmedv** [comment]
Now Expr supports bit operations. See https://expr-lang.org/docs/language-definition#bitwise-functions
