### ISSUE TITLE
Array comparison is no longer compatible with lower versions

### ISSUE THREAD

**Issue by fujiwaram** [expr-lang/expr#371]
Array comparison behavior is changed from v1.10.0.

e.g.
```golang
func main() {
	env := map[string]interface{}{
		"names": []string{"A", "B"},
	}
	code := `["A", "B"] == names`

	program, _ := expr.Compile(code, expr.Env(env))
	output, _ := expr.Run(program, env)
	fmt.Println(output)
}
```
- v1.9.0 or before
result: `true`
    ```golang
    []string{“A”, "B"} == []string{"A", "B"}
    ```
- v1.10.0 or after
result: `false`
    ```golang
    // internal type is []interface{}, so type mismatch
    []interface{}{“A”, "B"} == []string{"A", "B"}
    ```

v1.9.0: https://goplay.tools/snippet/tayU9IxLSFz
v1.10.0: https://goplay.tools/snippet/Ezau-zbCscu

**Comment by antonmedv** [comment]
The bytecode used is `OpEqual` and uses the same runtime.Equal fn: https://github.com/antonmedv/expr/blob/cb1f3459dd4705b6cbaf43069925d5e2c782fd6b/vm/runtime/generated.go#L11

Nothing is changed there. Can you try to debug?

**Comment by fmarcia** [comment]
I manage to insert the line below before calling reflect.DeepEqual, [at the end of runtime.Equal](https://github.com/antonmedv/expr/blob/master/vm/runtime/generated.go#L351):
```go
fmt.Printf("reflect.DeepEqual(%T, %T) == %v\n", a, b, reflect.DeepEqual(a, b))
```

v1.14.0 output:
```go
reflect.DeepEqual([]interface {}, []string) == false
```

v1.9.0 output:
```go
reflect.DeepEqual([]string, []string) == true
```

I hope it helps

**Comment by antonmedv** [comment]
So the problem not with comparison. But with turned off optimisation on converting []any to []string

**Comment by antonmedv** [comment]
Fixed! Not it is possible to do deep array comparison in expr.
