### ISSUE TITLE
Provide a way to define types via expr

### ISSUE THREAD

**Issue by antonmedv** [expr-lang/expr#480]
Now expr inherits types from "example" env. I may be cool to have a API to define types explicitly.

**Comment by antonmedv** [comment]
We can introduce those:

- types.Map: for giving a hint of map fields. 
- types.StrictMap: field hints, plus only defined keys are allowed.

**Comment by staugaard** [comment]
This would be a great feature. Any plans of implementing this?

**Comment by antonmedv** [comment]
Yes, this feature on the roadmap.

**Comment by antonmedv** [comment]
```go
	env := types.StrictMap{
		"foo": types.StrictMap{
			"bar": types.Int,
		},
	}
```
