### ISSUE TITLE
Transfer `antonmedv/expr` to `expr-lang/expr`

### ISSUE THREAD

**Issue by antonmedv** [expr-lang/expr#481]
I’m thinking of migrating main repo (this repo) to https://github.com/expr-lang/expr. 

What do you think? Should I?

**Comment by PranavPeshwe** [comment]
What is the motivation?

**Comment by antonmedv** [comment]
Tested move with https://github.com/antonmedv/module-test. Looks like users will need to upgrade the module path.

I think I will add a such banner to a new repo:

> [!IMPORTANT]
> The repository [github.com/antonmedv/expr](https://github.com/antonmedv/expr) moved to [github.com/**expr-lang**/expr](https://github.com/expr-lang/expr).

**Comment by PranavPeshwe** [comment]
@antonmedv JFYI, `https://expr.medv.io/#install` still says `go get github.com/antonmedv/expr`

**Comment by kkoreilly** [comment]
It is probably too late to revert now, but this rename is a violation of semantic versioning and results in all importers being unable to run `go get -u ./...` normally. Instead, they have to manually find and replace all instances of `github.com/antonmedv/expr` with `github.com/expr-lang/expr`, except for those in `go.mod` and `go.sum`, as that would result in checksum mismatches. In my case, I did replace the instances in `go.mod` and `go.sum`, meaning that I had to manually edit `go.sum` files in more than 10 repositories to remove security errors. This rename places a burden on importers that they should not expect to receive under the Go versioning and semantic versioning guidelines.

The only way you could have done this rename without violating semantic versioning would be to update the major version to 2 (with module URL `github.com/expr-lang/expr/v2`), which would have kept the previous version at `github.com/antonmedv/expr` fully functional. You could still theoretically do this, but the damage in terms of importers having to fix all of their imports is probably mostly already done, so it probably isn't worth it. However, if you did want to do this, you would release a new version, `v.15.7`, with `retract` directives in the `go.mod` file retracting `v.15.6` and `v.15.7`. Then, you would release `v2.0.0` with the module URL `github.com/expr-lang/expr/v2`.

**Comment by antonmedv** [comment]
> they should not expect to receive under the Go versioning and semantic versioning guidelines.

Go modules are badly designed. 

>  you would release v2.0.0 with the module URL github.com/expr-lang/expr/v2

I will never release v2 module. Same, for example, as Kubernetes team doing. Only v1. Again - go modules not great. 

>  this rename is a violation of semantic versioning

Semantic versioning is not a silver bullet. I never claimed I was following it. And I will not. Same, for example, as TypeScript.
