### ISSUE TITLE
Combine 2 arrays

### ISSUE THREAD

**Issue by lukas-vollmer** [expr-lang/expr#493]
Is there currently a way to combine arrays?

Something like this:
concat(["value1", "value2"], ["value3", "value4"]) or ["value1", "value2"] + ["value3", "value4"] 

Result:

["value1", "value2", "value3", "value4"]

**Comment by lukas-vollmer** [comment]
Sure @antonmedv, but I think its commonly enough to add it here as well

**Comment by antonmedv** [comment]
What should we add? append() or concat()? :)

**Comment by lukas-vollmer** [comment]
I think concat() would make more sense here, since append would only add the array as a new entry:
**concat:**
```
array1 = [1, 2, 3]
array2 = [4, 5, 6]
array3 = concat(array1, array2) -> [1, 2, 3, 4, 5, 6]
```

Append would be:
```
array1 = [1, 2, 3]
array2 = [4, 5, 6]
array3 = append(array1, array2) -> [1, 2, 3, [4, 5, 6]]
```

**Comment by lukas-vollmer** [comment]
Hmm just checked it for go. It seems different here xD

`package main

import (
    "fmt"
)

func main() {
    slice1 := []int{1, 2, 3}
    slice2 := []int{4, 5, 6}

    // Concatenating slice1 and slice2
    concatenatedSlice := append(slice1, slice2...)

    fmt.Println(concatenatedSlice) // Output: [1 2 3 4 5 6]
}`

**Comment by lukas-vollmer** [comment]
Ok append it is :)

**Comment by antonmedv** [comment]
I like concat()?

**Comment by annamedv** [comment]
I love JS, so will vote for concat(). And one element can be wrapped in array.

**Comment by elliottc** [comment]
Not sure if this deserves its own issue but I found myself wanting a way to merge maps as well. I've used [Python's dictionary unions](https://peps.python.org/pep-0584/) like this before.

**Comment by kuadrosx** [comment]
I think with slices.Concat added in Golang 1.22(to merge to slices), the name should be concat

**Comment by antonmedv** [comment]
So it will be concat

**Comment by antonmedv** [comment]
Added!
