### ISSUE TITLE
Access outer predicate item from inner nested predicate

### ISSUE THREAD

**Issue by danitrod** [expr-lang/expr#511]
For a specific use case, I would like to access an outer predicate item from inside a nested predicate. A simplified example, in the [expr playground](https://expr-lang.org/playground), would be this expression:
```
all(Posts, { any(.Comments, { .AuthorName == #Posts.Author.FirstName }) })
```
which doesn't compile as I can't access the `#Posts` pointer. In this simplified expression I would like to check if for all posts, there are any comments with the author name being the same as the post author's first name. Is there any way to do this currently with `expr`?

**Comment by antonmedv** [comment]
You can use variables for that.

    all(Posts, {let post = #; any(.Comments, { .AuthorName == post.Author.FirstName }) })

**Comment by antonmedv** [comment]
You can use variables for that.

    all(Posts, {let post = #; any(.Comments, { .AuthorName == post.Author.FirstName }) })

**Comment by danitrod** [comment]
Sounds good, that will solve my use case. Thank you

**Comment by antonmedv** [comment]
Added to a doc https://expr-lang.org/docs/language-definition#predicate
