### ISSUE TITLE
how to eval with ctx value

### ISSUE THREAD

**Issue by chyroc** [expr-lang/expr#513]
```
	ctx := context.WithValue(context.Background(), "a", "aaa")
	fmt.Println(expr.Eval(`ctx.a`, map[string]any{
		"ctx": ctx,
	}))
```

expected result:

```
aaa
```

but got:

```
<nil> cannot fetch a from *context.valueCtx (1:5)
 | ctx.a
 | ....^
```

**Comment by tw1nk** [comment]
shouldn't the script be be `ctx.Value("a")` ? I wouldn't recommend using the context for this though.

**Comment by antonmedv** [comment]
@tw1nk is right. Use `Context.Value(key any) any`.

Or add a patcher to modify `ctx.a` to `ctx.Value("a")` on compilation step.

**Comment by chyroc** [comment]
how to use patcher to modify ctx.a to ctx.Value("a")

**Comment by antonmedv** [comment]
https://expr-lang.org/docs/visitor-and-patch
