### ISSUE TITLE
Segfault with expr.WithContext

### ISSUE THREAD

**Issue by elliottc** [expr-lang/expr#529]
go 1.21, expr 1.15.8

From debugging it looked like type information didn't get set on the second `foo` call, then the `WithContext` visitor fails on that call. I wanted to have the context set on every `foo` call.

https://go.dev/play/p/_LCsz6-0PVV
```
package main

import (
	"context"
	"fmt"

	"github.com/expr-lang/expr"
)

func foo(ctx context.Context, n int) int {
	if ctx == nil {
		panic("wanted a context")
	}
	return n + 1
}

func main() {
	env := map[string]any{
		"ctx": context.Background(),
		"foo": foo,
	}
	options := []expr.Option{
		expr.Env(env),
		expr.WithContext("ctx"),
	}

	script := "foo(0) | foo()"
	prog, err := expr.Compile(script, options...)
	if err != nil {
		fmt.Println(err)
		return
	}

	out, err := expr.Run(prog, env)
	if err != nil {
		fmt.Println(err)
		return
	}

	fmt.Println(out)
}
```

**Comment by antonmedv** [comment]
Fixed in https://github.com/expr-lang/expr/commit/cda16c21633e49505535aa4c0b70d39fd9640a21

Also added your example as test case to prevent from happening in future.
