### ISSUE TITLE
Builtin mean function does not consider Operator "+" overload, and fails on json.Number array.

### ISSUE THREAD

**Issue by AndrewDK** [expr-lang/expr#530]
If I've defined an Operator "+" that knows how to add the json.Number type, I'd like to be able to do a mean on an array of json.Numbers. Instead, while attempting to sum, mean determines that json.Number is not an int or float type and fails.

**Comment by antonmedv** [comment]
Yes, this is due to the reason what mean() func takes integers or floats arguments. Not json.Number. 

If you added + operator overload, expr will convert this expression:

```
n1 + n2
```

Into

```
addJsonNumbers(n1, n2)
```

And depending on what your functions addJsonNumbers returns it mean() call can fail:

```
mean(addJsonNumbers(n1, n2), addJsonNumbers(n1, n2))
```
