### ISSUE TITLE
Question on thread safety of concurrent evaluations

### ISSUE THREAD

**Issue by carlosabalde** [expr-lang/expr#531]
Is ok to share the result of `expr.Compile()` across goroutines for concurrent evaluation? I din't find anything in the docs about it; just one mention in an issue. However some tests seem to indicate that it is ok, but I would like to be sure. Thanks!

**Comment by antonmedv** [comment]
Yes! Expr's vm.Program is thread safe. You can run compiled program in multiple threads via [expr.Run()](https://pkg.go.dev/github.com/expr-lang/expr#Run). 

We have a test in CI to catch race condition in running program in multiple threads.

> [!caution]
> The vm.VM is not thread safe. Althought you can use a single vm instance to rerun programs.
> If needed you can create a vm per thread. The expr.Run() creates a new vm for each call.
