### ISSUE TITLE
fromPairs(toPairs({a: 1})) doesn't work

### ISSUE THREAD

**Issue by 37acoder** [expr-lang/expr#532]
json: unsupported type: map[interface {}]interface {}

<img width="970" alt="image" src="https://github.com/expr-lang/expr/assets/22274895/834130a7-f964-4e87-9188-6f35b85ce7c6">

**Comment by antonmedv** [comment]
This is just a playground problem. Go's json package does not support marshaling map[any]any to json (only map[string]any). I have plans to refactor playground and get way from json as output. 

You still can get results in playground by wrapping in string() func:

```
string(fromPairs(toPairs({a: 1})))
```

> [!tip]
> Use a pipe operator for better readability:
> ```
> toPairs({a: 1}) | fromPairs() | string()
> ```
