### ISSUE TITLE
Issue overriding builtin functions?

### ISSUE THREAD

**Issue by carlosabalde** [expr-lang/expr#534]
It looks like overriding builtin functions is not working properly in 1.15.8.

For example, using this simple program:

```
func main() {
	env := map[string]interface{}{
		"foo": map[string]interface{}{
			"bar": 42,
			"baz": 3.14,
		},
	}

	program, err := expr.Compile(
		`foo | toJSON()`,
		expr.Env(env),
		expr.DisableBuiltin("toJSON"),
		expr.Function(
			"toJSON",
			func(args ...any) (any, error) {
				if len(args) != 1 {
					return nil, fmt.Errorf("invalid number of arguments: %d", len(args))
				}

				jsonBytes, err := json.Marshal(args[0])
				if err != nil {
					return nil, err
				}
				return string(jsonBytes), nil
			},
			new(func(any) string)))
	if err != nil {
		panic(err)
	}

	var result interface{}
	result, err = expr.Run(program, env)
	if err != nil {
		panic(err)
	}
	if _, ok := result.(string); !ok {
		panic("result is not string")
	}

	fmt.Println(result)
}
```

I'd expect this output:

```
{"bar":42,"baz":3.14}
```

But this is what I get (i.e. the original `toJSON()` implementation is used):

```
{
  "bar": 42,
  "baz": 3.14
}
```

Of course, adding the builtin using a new name like `toSingleLineJSON` works as expected. Is this a bug or am I missing something? Thanks!

**Comment by antonmedv** [comment]
Fixed in 564b637c224da220c648e399669cb8c4e87d73fa. It was a bug with parsing the pipe operator call. 

I also added a test what all of built-in functions can be overridden and used inside the pip.e
