### ISSUE TITLE
Accessing map fields with invalid names

### ISSUE THREAD

**Issue by elliottc** [expr-lang/expr#538]
go 1.21, expr 1.15.8

I wanted to access map fields using the dot syntax where the keys are numbers, for example:
```
{1:2}.1
// or {"1":2}.1
```
> unexpected token Number(".1") (1:6)

There's the alternative `{1:2}["1"]` but I was hoping to be able to use the optional chaining `?.` syntax to access fields in a map like this a few levels deep. As a workaround I'm doing this:
```
let vals = {...};
((vals["1"]??{})["2"]??{})["3"]
// instead of vals.1?.2?.3
```

**Comment by antonmedv** [comment]
I'm going to add `arr?.[0]` syntax as in JS.
