### ISSUE TITLE
Versions after v1.15.6 disable access to `vm.Program.Location`

### ISSUE THREAD

**Issue by buixor** [expr-lang/expr#546]
ref: https://github.com/expr-lang/expr/discussions/544

with [v1.15.6](https://github.com/expr-lang/expr/releases/tag/v1.15.6), some fields of vm.Program aren't accessible/public anymore, such as Locations.

I used to rely on the Locations field to fetch the source code line number associated with a given instruction pointer. By using vm.Step(), vm.Position() and the Locations of vm.Program, it allows to display debug/code to users when debugging their expression in [crowdsec](https://github.com/crowdsecurity/crowdsec).

Making this field public again would allow to continue to provide such a feature!

**Comment by antonmedv** [comment]
Added [program.Locations()](https://github.com/expr-lang/expr/commit/e53cefe2ef29c793f3867e4568e1c81dc76a50ad)
