### ISSUE TITLE
Allow to use operator tokens as functions `contains()`

### ISSUE THREAD

**Issue by Q16G** [expr-lang/expr#572]
Could it be possible to add and disable an Operator and rewrite it entirely with function

**Comment by Q16G** [comment]
What I mean by that is to rewrite the operand with a function after the change is disabled, and to re-specify the logic, for example, contains, it used to be "a" contains "b" can it now be "contains" ("a","b")

**Comment by antonmedv** [comment]
I think allowing to use some operators as function is a bad practice. So I'm going to say not to this.
