### ISSUE TITLE
Logical operation against array functions not working as expected in v1.16

### ISSUE THREAD

**Issue by rassakhatsky** [expr-lang/expr#624]
Affected version: 1.16+ (v1.15 works fine).
I'm getting a strange issue while trying to use logical operation against array functions. `v1.16` has this issue, `v1.15` works fine.
Here is a simple snippet:
```golang

	type tag struct {
		Name string
	}

	type item struct {
		Tags []tag
	}

	i := item{
		Tags: []tag{
			{Name: "one"},
			{Name: "two"},
		},
	}

	rule := `[
true && true, 
one(Tags, .Name in ["one"]), 
one(Tags, .Name in ["two"]), 
one(Tags, .Name in ["one"]) && one(Tags, .Name in ["two"])
]`
	resp, err := expr.Eval(rule, i)


```
Expected Result in `v1.15`: [true, true, true, true].
Actual Result in `v1.16`: [true, true, true, false].

**Comment by antonmedv** [comment]
I guess this is due to incorrect optimisation in compiler. PTAL @bizywizy
