### ISSUE TITLE
it is really fast. question on language compatibility issue...

### ISSUE THREAD

**Issue by sprappcom** [expr-lang/expr#671]
cel-go has support for c++ etc.

was wondering any caveats to look out for if someday ( a distant someday ) that expr is supported for use in rustlang?

**Comment by antonmedv** [comment]
Right now, we have plans to release a JS version. Rust version of lang is probably in a future too.

**Comment by sprappcom** [comment]
@antonmedv not really interested in a js version but rustlang will be very useful.

thx by the way.

**Comment by 5idu** [comment]
@antonmedv Are there any recent updates to the Rust version? tks.

**Comment by antonmedv** [comment]
Not yet.
