### ISSUE TITLE
Create custom function with many arguments

### ISSUE THREAD

**Issue by sandeep-velichety** [expr-lang/expr#696]
I am trying to create a library of custom functions whch i would like to add based on use case where a expression can have mutli functional call and multi variable calls. I was trying to a simple add with two variables. It failing in identifying the variable.

package main

import (
	"fmt"

	"github.com/expr-lang/expr"
)

type CustomFunctions struct {
}

func (e *CustomFunctions) Add(args ...any) (any, error) {
	var result float64
	for i := 0; i < len(args); i++ {
		switch args[0].(type) {
		case int:
			result += float64(args[i].(int))
		case float64:
			result += args[i].(float64)
		}
	}
	return result, nil
}

func main() {
	code := `Add(a,b)`

	env := CustomFunctions{}
	program, err := expr.Compile(code,
		expr.Function("Add", env.Add, new(func() any)),
		expr.Env(env))
	if err != nil {
		panic(err)
	}

	variables := map[string]interface{}{"a": 10, "b": 20}
	output, err := expr.Run(program, variables)
	if err != nil {
		panic(err)
	}
	fmt.Println(output)
}

Here i am adding `Add(a,b)` but this could be more something like `Add(a,b,c)` or Add(a,b,c,d)` where i can pass the variables using env. Can something like this be done using expr

**Comment by antonmedv** [comment]
You need to use same env on compile and run. If you use struct - use struct. Map - use map.
