### ISSUE TITLE
Unable to access array item using index and not able to use apply map/filter/any on array item.

### ISSUE THREAD

**Issue by akinaza** [expr-lang/expr#720]
I am using expr-lang playground to filter some data. after filtering it came as an array output. when I print type of output it shows "array".
But when I try to access element of array using index I get an error "type unknown[int] is undefined". 
Also when I try to apply filter then I get an error "builtin filter takes only array (got unknown)", similarly for map and all.

I am attaching the json data and the expressions along with the screen shot of the outputs. 

[data.json](https://github.com/user-attachments/files/17409521/data.json)

expressions "let plates = filter(BODY.enrichments.MAKEMODEL, {let makemodelvehicles = #.makeModel; any(BODY.data.policy.vehicles, {let vehicle=#; any(makemodelvehicles, {lower(vehicle.make) == lower(.make) and (lower(vehicle.model) contains lower(.model) or split(lower(vehicle.model), ' ')[0] contains split(lower(.model), ' ')[0]) })})})[0].licensePlate.candidates;"

![Screenshot 2024-10-17 145333](https://github.com/user-attachments/assets/994ef2fc-03bb-4efc-a18c-a63e56735224)
![Screenshot 2024-10-17 145348](https://github.com/user-attachments/assets/ac7c7b6a-9d16-4f5f-9b91-e2f122d899dd)
![Screenshot 2024-10-17 145400](https://github.com/user-attachments/assets/02a820b9-a6c6-46fd-a666-c0a3b2ae621d)
![Screenshot 2024-10-17 145416](https://github.com/user-attachments/assets/2bd3985c-29ae-46b6-9a88-4ee19d213a58)

**Comment by antonmedv** [comment]
Strange. Works for me:

<img width="1470" alt="image" src="https://github.com/user-attachments/assets/cbb04c8e-8a6c-4710-869f-f80ec1c43684">

**Comment by antonmedv** [comment]
Got the error with expr `plates[0].licensePlate.candidates[0]`. Looks like there is some problem with the type checker. 

```
type unknown[int] is undefined (2:34)
 | plates[0].licensePlate.candidates[0]
 | .................................^
 ```

**Comment by antonmedv** [comment]
Found simpler expression with the same error:
```

**Comment by antonmedv** [comment]
So the problem in the Playground:
<img width="1154" alt="image" src="https://github.com/user-attachments/assets/9d150c37-f67e-4caa-9d93-b9e97437bae9">

licensePlate in playground marked as any and type checker treats it as unknown.
