### ISSUE TITLE
memory budget exceeded

### ISSUE THREAD

**Issue by ChiragRayani** [expr-lang/expr#721]
I have used below expression

`let two = {"one":1000000};
let resultMap = {0 : two.one in 1000000..2000000}; resultMap`

and getting below error

`memory budget exceeded (2:40)
 | let resultMap = {0 : two.one in 1000000..2000000}; resultMap
 | .......................................^`

**Comment by antonmedv** [comment]
`1000000..2000000` creates a huge array. Expr prevents those kind of misuse. 

But sometimes Expr can modify code to make it faster: `42 in 1000000..2000000` will be converted to `1000000 <= 42 <= 2000000`.

Expr will not modify code if type of variable is `any`:

```js
let x = [1, "a"][0]; // Trick type checker to thinking x is of "any" type.
x in 1000000..2000000 // Will result in error.
```

**Comment by ChiragRayani** [comment]
but then how its working when i'm adding a patcher

`binary, ok := (*node).(*ast.BinaryNode)
	if ok {
		if binary.Operator == "in" {
			ast.Patch(node, &ast.BinaryNode{
				Operator: binary.Operator,
				Left: &ast.ConditionalNode{
					Cond: &ast.BinaryNode{
						Left:     binary.Left,
						Operator: "==",
						Right:    &ast.NilNode{},
					},
					Exp1: &ast.IntegerNode{Value: 0},
					Exp2: binary.Left,
				},
				Right: binary.Right,
			})
		}
	}`

**Comment by antonmedv** [comment]
by replacing ==
